# Generated by Django 5.2.6 on 2025-11-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscriptionplan'),
        ('news', '0003_subscriptiontable'),
    ]

    operations = [
    ]
