# Generated by Django 5.2.6 on 2025-11-10 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_newstable_category_delete_newscategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
