# Generated by Django 5.2.6 on 2025-11-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstable',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
