# Generated by Django 5.2.6 on 2025-11-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_newsvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsvideo',
            name='category',
            field=models.CharField(choices=[('Latest News', 'Latest News'), ('News', 'News'), ('India News', 'India News'), ('World News', 'World News'), ('Local News', 'Local News'), ('Sports News', 'Sports News'), ('Film Industry News', 'Film Industry News'), ('Political News', 'Political News'), ('Crime News', 'Crime News'), ('Accounts News', 'Accounts News'), ('Market News', 'Market News'), ('Health and Wellness', 'Health and Wellness'), ('Technology and Science', 'Technology and Science'), ('Business and Finance', 'Business and Finance')], default='Latest News', max_length=50),
        ),
        migrations.AddField(
            model_name='newsvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
    ]
